# Generated by Django 4.2.5 on 2023-10-05 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Alumno', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Director', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Grupo', models.IntegerField()),
                ('curso', models.CharField(max_length=200)),
                ('dias_semana', models.CharField(max_length=200)),
                ('hora_inicio', models.DateTimeField()),
                ('duracion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Guardian', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Instructor', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Sede', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('codigo_postal', models.IntegerField()),
                ('id_Guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.guardian')),
            ],
        ),
        migrations.CreateModel(
            name='Secretarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Secretario', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('id_Director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.directores')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Inscripcion', models.IntegerField()),
                ('fecha_inscripcion', models.DateField()),
                ('id_Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.alumnos')),
                ('id_Grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.grupos')),
            ],
        ),
        migrations.AddField(
            model_name='grupos',
            name='id_Instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.instructores'),
        ),
        migrations.AddField(
            model_name='grupos',
            name='id_Sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.sedes'),
        ),
        migrations.AddField(
            model_name='directores',
            name='id_Sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.sedes'),
        ),
    ]
