# Generated by Django 4.2.5 on 2023-10-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_administradores_remove_secretarios_id_director_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sedes',
            old_name='municipio',
            new_name='ubicacion',
        ),
    ]
