# Generated by Django 4.2.5 on 2023-10-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_municipio_sedes_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sedes',
            name='id_Administrador',
        ),
    ]
