# Generated by Django 4.2.5 on 2023-10-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administradores',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='apellido_materno',
            field=models.CharField(default='admin', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='apellido_paterno',
            field=models.CharField(default='admin', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default='2023-10-18'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombre',
            field=models.CharField(default='admin', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
