# Generated by Django 4.2.5 on 2023-10-19 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_delete_administradores_userprofile_apellido_materno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
