# Generated by Django 4.2.5 on 2023-10-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='apellido_materno',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='apellido_paterno',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fecha_nacimiento',
            field=models.DateField(default='2023-10-18'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
