# Generated by Django 4.2.7 on 2023-11-23 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_dias_semana_gruposdias_rename_id_sede_grupos_sede_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='login.userprofile'),
        ),
    ]
